export { default as one } from '../assets/article-image/image_one.png'
export { default as two } from '../assets/article-image/image_two.png'
export { default as three } from '../assets/article-image/image_three.png'
export { default as four } from '../assets/article-image/image_four.png'
export { default as five } from '../assets/article-image/image_five.png'
export { default as six } from '../assets/article-image/image_six.png'
export { default as seven } from '../assets/article-image/image_seven.png'
export { default as eight } from '../assets/article-image/image_eight.png'
export { default as nine } from '../assets/article-image/image_nine.png'
export { default as ten } from '../assets/article-image/image_ten.png'
export { default as eleven } from '../assets/article-image/image_eleven.png'
export { default as twelve } from '../assets/article-image/image_twelve.png'
export { default as thirteen } from '../assets/article-image/image_thirteen.png'
export { default as fourteen } from '../assets/article-image/image_fourteen.png'
export { default as fifteen } from '../assets/article-image/image_fifteen.png'

